language: python

python:
  - 2.7

before_install:
  - git submodule update --init --recursive

install:
  - "pip install -Ur requirements.txt"

before_script:
  - sh -e /etc/init.d/xvfb start

script: py.test tests/desktop -s -n 4 -v -r fsxXR --baseurl=https://marketplace-dev.allizom.org --driver=firefox --destructive -m "not credentials and not action_chains"

env:
  - DISPLAY=':99.0'

notifications:
  email:
    - webqa-ci@mozilla.org
